/** Imágenes en `public/brand/{n}.png` y nombre mostrado bajo cada tarjeta. */
export const CATALOG_CAROUSEL_ITEMS = [
  { image: 1, name: "COCO GLOW" },
  { image: 2, name: "AVOSILK" },
  { image: 3, name: "BANAGLOW" },
  { image: 4, name: "ONION BOOST" },
  { image: 5, name: "CHONTAHAIR" },
  { image: 6, name: "YUKARESS" },
  { image: 7, name: "GUAVAMASK" },
  { image: 8, name: "GUNABA LUXE" },
  { image: 9, name: "PAPAYASMOOTH" },
  { image: 10, name: "" },
  { image: 11, name: "BOTANIHAIR BLEND" },
  { image: 12, name: "BOTANIHAIR BLEND" },
  { image: 13, name: "BOTANIHAIR BLEND" },
  { image: 14, name: "BOTANIHAIR BLEND" },
  { image: 15, name: "BOTANIHAIR BLEND" },
  { image: 16, name: "VIGOR COFFE" },
  { image: 17, name: "CHOCOHAIR GLOW" },
  { image: 18, name: "BEETROOTRADIANCE" },
  { image: 19, name: "CARO TRESS ELIXIR" },
  { image: 20, name: "ROSVITALHAIR" },
  { image: 21, name: "ALOE FRESH HAIR" },
  { image: 22, name: "MANGO GLOW HAIR" },
  { image: 23, name: "AFROGLOW" },
  { image: 24, name: "HERBAL ROOTS" },
  { image: 25, name: "TROPICAL REPAIR" },
] as const;
